### PR TITLE
Typescript

### LINKED ISSUE #14: Typescript pull request?
I created a fork of this project and converted it to Typescript; would you be interested in a pull request to integrate typescript into this project?

### PR DESCRIPTION
**Pull request by neferin12**
As mentioned in my issue I opened earlier, I changed the Code to TypeScript. Requiring the code can be done like before by calling `require("keycloak-backend)(config)` or alternatively when using Typescript/Modules by importing the new Keycloak class and instanciating it:
```ts
import Keycloak from "keycloak-backend";
const keycloak = new Keycloak({
    "realm": "realm-name",
    "keycloak_base_url": "https://keycloak.example.org",
    "client_id": "super-secure-client",
    "username": "user@example.org",
    "password": "passw0rd",
    "is_legacy_endpoint": false
});
```
No logic was changed, I hope I got all the types right.

Closes #14

### CODE REVIEW

**Comment by neferin12** [comment]
Okay, there is a problem:
using the notation for getting the keycloak object I wrote down in my pull request necessitates also changing the commonjs notation to
```js
const Keycloak = require("keycloak-backend").default
const keycloak = new Keycloak(config)
```

Alternatively the commonjs variant would still change to:
```js
const keycloak = require("keycloak-backend").default(config)
```
In the latter way it would change the typescript to:
```ts
import Keycloak from "keycloak-backend"
const keycloak = Keycloak(config)
```

Either way this would mean a breaking change and I don't know If you'd be open to that. I also have to do an additional commit either way, but I wanted to await your feedback for that

**Comment by jkyberneees** [comment]
> ```js
> .default
> ```

Hi @neferin12, thanks for pushing this topic forward, having to use `.default` is expected, we can release a major version for this. I will get back to review your PR ASAP. 

Regards

**Comment by jkyberneees** [comment]
Hi @neferin12 , thanks for contributing. I was checking your proposal, please note below my recommendations on the code style:
- Please define classes, interfaces and types outside classes and methods preferable. Export those as well. 
- Consider following https://google.github.io/styleguide/tsguide.html TS guide and recommendations 

Regards

**Comment by neferin12** [comment]
Thank you @jkyberneees for your feedback, I'll change the code accordingly in the next couple of days, as soon as I have the time.

**Comment by neferin12** [comment]
I read through the Google TS Styleguide and changed the files accordingly, I hope I didn't miss something.
I decided against exporting the interfaces at the top of the `AccessToken.ts` file, as they can/are only used internally, so there would be no use exporting them in my opinion.

**Review by lucakiebel — APPROVED** [review]

**Pull request merged**
